# Tabela de tokens
tokens = [
    {'tag': 256, 'lexeme': 'and'},
    {'tag': 257, 'lexeme': 'basic'},             
    {'tag': 257, 'lexeme': 'int', 'width': 4},
    {'tag': 257, 'lexeme': 'float', 'width': 8},
    {'tag': 258, 'lexeme': 'break'},
    {'tag': 259, 'lexeme': 'do'},
    {'tag': 260, 'lexeme': 'else'},
    {'tag': 261, 'lexeme': 'eq'},
    {'tag': 262, 'lexeme': 'false'},
    {'tag': 263, 'lexeme': 'ge'},
    #{'tag': 264, 'lexeme': f'{valueOrSymb}'},
    {'tag': 265, 'lexeme': 'if'},
    {'tag': 266, 'lexeme': 'index'},
    {'tag': 267, 'lexeme': 'le'},
    {'tag': 268, 'lexeme': 'minus'},
    {'tag': 269, 'lexeme': 'ne'},
    # {'tag': 270, 'value': f'{lexeme}'},
    {'tag': 271, 'lexeme': 'or'},
    {'tag': 272, 'lexeme': 'real'},
    {'tag': 273, 'lexeme': 'temp'},
    {'tag': 274, 'lexeme': 'true'},
    {'tag': 275, 'lexeme': 'while'},
]

# Tabela de simbolos
symbols = [
    {'tag': '*'},
    {'tag': '+'},
    {'tag': '/'},
    {'tag': '-'},
    {'tag': '<'},
    {'tag': '>'},
    {'tag': '<='},
    {'tag': '>='},
    {'tag': '!='},
    {'tag': '=='},
    {'tag': '**'},
    {'tag': '='},
    {'tag': '!'},
    {'tag': '%'},
    {'tag': '&'},
    {'tag': '('},
    {'tag': ')'},
    {'tag': '['},
    {'tag': ']'},
    {'tag': '{'},
    {'tag': '}'},
    {'tag': ';'},
    {'tag': ':'}, 
    {'tag': ','}
]